apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: mysql:latest
        name: mysql
        args:
            - "--default-authentication-plugin=mysql_native_password"
        ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
