apiVersion: v1
kind: Namespace
metadata:
  name: kuma-app
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: kuma-app
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
      - name: api-server
        image: api-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: kuma-app
spec:
  type: LoadBalancer
  ports:
  - name: api-server-port
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-server
